name: stocks_core
description: "A new Flutter package project."
version: 0.0.1

environment:
  sdk: '>=3.4.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  dio: ^5.5.0+1
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  fpdart: ^1.1.0
  get_it: ^7.7.0
  go_router: ^14.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0

flutter:
